import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../providers/language_provider.dart';

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _values = {
    'id': {
      'nav_home': 'Home',
      'nav_dashboard': 'Dashboard',
      'nav_features': 'Fitur',
      'nav_admin': 'Admin',
      'nav_approval': 'Approval',
      'nav_profile': 'Profil',
      'approval_subtitle': 'Persetujuan dan status notifikasi Anda',
      'approval_notification_title': 'Notifikasi',
      'approval_notification_unread': '{count} notifikasi belum dibaca',
      'approval_notification_summary': '{count} notifikasi tersedia',
      'approval_action_section': 'Status & Persetujuan',
      'approval_empty_title': 'Belum ada akses approval',
      'approval_empty_message':
          'Jika Anda diberi permission approval atau transaksi, menu terkait akan muncul di sini.',
      'approval_badge_approve': 'APPROVE',
      'approval_badge_status': 'STATUS',
      'approval_leave_title': 'Cuti',
      'approval_leave_subtitle':
          'Lihat status cuti atau proses persetujuan cuti.',
      'approval_claims_title': 'Klaim Biaya',
      'approval_claims_subtitle':
          'Pantau status klaim atau proses persetujuan klaim.',
      'approval_overtime_title': 'Lembur',
      'approval_overtime_subtitle':
          'Pantau pengajuan lembur dan status persetujuannya.',
      'approval_tasks_title': 'Tugas',
      'approval_tasks_subtitle': 'Lihat status dan progres tugas Anda.',
      'dashboard_cached_banner':
          'Dashboard sedang menampilkan data cache terakhir karena server belum bisa diakses.',
      'dashboard_stat_total_employees': 'Total Karyawan',
      'dashboard_stat_attendance_today': 'Absensi Hari Ini',
      'dashboard_stat_on_leave_today': 'Cuti Hari Ini',
      'dashboard_stat_new_hires': 'Karyawan Baru',
      'dashboard_stat_active': 'Aktif',
      'dashboard_stat_present_today': 'Hadir hari ini',
      'dashboard_stat_leave_today': 'Cuti hari ini',
      'dashboard_stat_this_month': 'Bulan ini',
      'dashboard_welcome_back': 'Selamat datang kembali,',
      'dashboard_good': 'Selamat',
      'dashboard_morning': 'pagi',
      'dashboard_afternoon': 'siang',
      'dashboard_evening': 'malam',
      'dashboard_summary_today': 'Berikut ringkasan Anda hari ini',
      'dashboard_total_employees_short': 'total karyawan',
      'dashboard_quick_actions': 'Aksi Cepat',
      'dashboard_guide': 'Panduan',
      'dashboard_quick_action_guide_title': 'Panduan Aksi Cepat',
      'dashboard_quick_action_guide_message':
          'Scan paling cocok dipakai untuk absensi QR atau checkpoint cabang. Saat backend scanner khusus belum ada, tombol itu diarahkan ke Clock In agar tetap berguna.',
      'dashboard_action_scan': 'Scan',
      'dashboard_action_scan_purpose':
          'Akses tercepat untuk QR attendance atau checkpoint kantor. Saat ini diarahkan ke Clock In cepat.',
      'dashboard_action_leave': 'Cuti',
      'dashboard_action_leave_purpose':
          'Masuk langsung ke pengajuan cuti dan riwayat cuti Anda.',
      'dashboard_action_reports': 'Laporan',
      'dashboard_action_reports_purpose':
          'Buka laporan claim dan reimbursement untuk monitoring pengeluaran tim.',
      'dashboard_action_add_employee': 'Tambah Karyawan',
      'dashboard_action_add_employee_purpose':
          'Input data karyawan baru tanpa masuk ke menu admin yang lebih dalam.',
      'dashboard_recent_activities': 'Aktivitas Terbaru',
      'dashboard_view_all': 'Lihat Semua',
      'dashboard_no_recent_activities': 'Belum ada aktivitas terbaru',
      'dashboard_upcoming_events': 'Rapat Mendatang',
      'dashboard_manage': 'Kelola',
      'dashboard_event_load_failed': 'Rapat belum bisa dimuat.',
      'dashboard_retry': 'Coba Lagi',
      'dashboard_no_upcoming_events': 'Belum ada rapat mendatang.',
      'dashboard_event_empty_hint':
          'Buat rapat lalu pilih siapa yang diundang dari Rapat.',
      'dashboard_create_event': 'Buat Rapat',
      'dashboard_no_event_access': 'Akun Anda belum memiliki akses ke Rapat.',
      'dashboard_all_employees': 'Semua karyawan',
      'dashboard_you_are_invited': 'Anda diundang',
      'dashboard_no_notifications': 'Tidak ada notifikasi',
      'dashboard_notifications': 'Notifikasi',
      'dashboard_mark_all_read': 'Tandai semua sudah dibaca',
      'dashboard_view_all_notifications': 'Lihat semua notifikasi ({count})',
      'dashboard_loading': 'Memuat dashboard Anda...',
      'dashboard_error_title': 'Ups! Terjadi kesalahan',
      'dashboard_try_again': 'Coba Lagi',
      'dashboard_just_now': 'Baru saja',
      'dashboard_minutes_ago': '{count} menit yang lalu',
      'dashboard_hours_ago': '{count} jam yang lalu',
      'dashboard_days_ago': '{count} hari yang lalu',
      'dashboard_duration_label': 'Durasi',
      'dashboard_duration_day': 'hari',
      'dashboard_duration_days': 'hari',
      'dashboard_today_label': 'Hari ini',
      'dashboard_start_time': 'Jam Masuk',
      'dashboard_end_time': 'Jam Pulang',
      'dashboard_record_time': 'Record Time',
      'dashboard_view_more': 'Lihat Detail',
      'dashboard_hide_detail': 'Sembunyikan Detail',
      'dashboard_shift_label': 'Shift',
      'dashboard_favorite_menu': 'Favorite Menu',
      'dashboard_company_information': 'Informasi Perusahaan',
      'dashboard_attendance_ready': 'Siap absensi',
      'dashboard_attendance_active': 'Sedang bekerja',
      'dashboard_attendance_complete': 'Absensi lengkap',
      'dashboard_attendance_pending_sync': 'Menunggu sinkronisasi',
      'feature_no_active_title': 'Belum ada fitur aktif',
      'feature_no_active_message':
          'Role Anda belum memiliki modul yang aktif di tab Feature. Hubungi administrator jika ada modul yang seharusnya muncul.',
      'feature_header_title': 'Jelajahi Fitur',
      'feature_header_subtitle':
          'Semua yang Anda butuhkan untuk mengelola pekerjaan',
      'feature_search_hint': 'Cari fitur...',
      'feature_footer_count': '{count} fitur tersedia',
      'feature_footer_subtitle':
          'Tab Feature dan Admin sekarang otomatis mengikuti permission akun Anda.',
      'feature_submenu_hint': 'Pilih submenu yang ingin dibuka.',
      'feature_no_submenu_access':
          'Akun Anda belum memiliki akses ke submenu yang tersedia.',
      'feature_submenu_available_count': '{count} menu tersedia',
      'feature_empty_title': 'Fitur tidak ditemukan',
      'feature_empty_search':
          'Tidak ada fitur yang cocok dengan pencarian "{query}".',
      'feature_empty_all':
          'Tidak ada fitur yang aktif untuk role Anda saat ini.',
      'feature_empty_category':
          'Tidak ada fitur aktif pada kategori {category}.',
      'feature_category_all': 'Semua',
      'feature_category_financial': 'Keuangan',
      'feature_category_core_hr': 'HR Inti',
      'feature_category_operations': 'Operasional',
      'feature_category_development': 'Pengembangan',
      'feature_category_workspace': 'Workspace',
      'feature_label_payroll': 'Payroll',
      'feature_label_payslip': 'Slip Gaji',
      'payroll_settings': 'Pengaturan Payroll',
      'payroll_menu_payroll': 'Slip Gaji',
      'payroll_process': 'Payroll',
      'payroll_pph_report': 'Laporan PPh',
      'payroll_submenu_hint': 'Pilih menu payroll yang ingin dibuka.',
      'feature_label_leave': 'Manajemen Cuti',
      'feature_label_attendance': 'Absensi',
      'feature_label_my_location': 'Lokasi Saya',
      'feature_label_claims': 'Klaim Biaya',
      'feature_label_overtime': 'Permintaan Lembur',
      'feature_label_performance': 'Performa',
      'feature_label_kpi': 'KPI',
      'kpi_master': 'Master KPI',
      'kpi_evaluation_list': 'Daftar Evaluasi',
      'kpi_department_goals': 'Target Departemen',
      'kpi_employee_goals': 'Target Karyawan',
      'kpi_submenu_hint': 'Pilih menu KPI yang ingin dibuka.',
      'kpi_mobile_placeholder':
          'Menu ini sudah mengikuti permission akun Anda. Tampilan detail mobile untuk modul KPI sedang disiapkan.',
      'feature_label_recruitment': 'Rekrutmen',
      'feature_label_applications': 'Lamaran',
      'feature_label_recruitment_ops': 'Operasional Rekrutmen',
      'recruitment_page_title': 'Rekrutmen',
      'recruitment_page_subtitle':
          'Kelola lowongan pekerjaan dan pantau proses lamaran kandidat.',
      'recruitment_tab_pipeline': 'Pipeline',
      'recruitment_tab_applications': 'Lamaran',
      'recruitment_pipeline_title': 'Pipeline Rekrutmen',
      'recruitment_pipeline_subtitle':
          'Pantau lowongan terbuka dan progres kandidat',
      'recruitment_candidate_pipeline': 'Pipeline Kandidat',
      'recruitment_open_positions': 'Posisi Terbuka',
      'recruitment_no_open_positions': 'Tidak ada posisi terbuka.',
      'recruitment_recent_applications': 'Lamaran Terbaru',
      'recruitment_no_applications': 'Belum ada lamaran.',
      'recruitment_post_job': 'Buat Lowongan Baru',
      'recruitment_add_application': 'Tambah Lamaran',
      'recruitment_new_application': 'Lamaran Baru',
      'recruitment_select_department': 'Pilih Departemen',
      'recruitment_select_position': 'Pilih Posisi',
      'recruitment_select_urgency': 'Pilih Urgensi',
      'recruitment_urgency_label': 'Urgensi',
      'recruitment_urgency_high': 'Tinggi',
      'recruitment_urgency_medium': 'Sedang',
      'recruitment_urgency_low': 'Rendah',
      'recruitment_job_requirements': 'Persyaratan Pekerjaan',
      'recruitment_requirement_hint': 'Masukkan requirement pekerjaan...',
      'recruitment_full_name': 'Nama Lengkap *',
      'recruitment_email': 'Email *',
      'recruitment_phone': 'Telepon *',
      'recruitment_department': 'Departemen *',
      'recruitment_position': 'Posisi *',
      'recruitment_no_file_selected': 'Belum ada file dipilih',
      'recruitment_file_selected_success': 'File berhasil dipilih',
      'recruitment_file_select_error': 'Gagal memilih file: {error}',
      'recruitment_supported_formats':
          'Format yang didukung: PDF, DOC, DOCX (Maks. 2MB)',
      'recruitment_fill_all_fields': 'Mohon lengkapi semua field',
      'recruitment_fill_application_fields':
          'Mohon lengkapi semua field dan upload CV',
      'recruitment_job_posted_success': 'Lowongan berhasil dibuat',
      'recruitment_application_submitted_success': 'Lamaran berhasil dikirim',
      'recruitment_failed': 'Gagal: {error}',
      'recruitment_unknown_error': 'Error tidak diketahui',
      'recruitment_error': 'Error: {error}',
      'recruitment_submit': 'Kirim',
      'recruitment_save': 'Simpan',
      'recruitment_cancel': 'Batal',
      'recruitment_update_status': 'Ubah Status',
      'recruitment_status_updated': 'Status diperbarui ke {status}',
      'recruitment_cv_unavailable': 'CV tidak tersedia',
      'recruitment_cv_document': 'Dokumen CV',
      'recruitment_cv_available': 'CV tersedia untuk diunduh',
      'recruitment_download_started': 'Download dimulai',
      'recruitment_download_cv': 'Download CV',
      'recruitment_close': 'Tutup',
      'recruitment_conversion_rate': 'Rasio Konversi',
      'recruitment_avg_time_to_hire': 'Rata-rata Waktu Rekrutmen',
      'recruitment_days': 'hari',
      'recruitment_position_not_specified': 'Posisi belum ditentukan',
      'recruitment_applied_prefix': 'Melamar',
      'recruitment_view_cv': 'Lihat CV',
      'recruitment_status_applied': 'Melamar',
      'recruitment_status_screening': 'Screening',
      'recruitment_status_interview': 'Interview',
      'recruitment_status_offer': 'Penawaran',
      'recruitment_status_hired': 'Diterima',
      'recruitment_status_rejected': 'Ditolak',
      'recruitment_ops_page_title': 'Operasional Rekrutmen',
      'recruitment_ops_page_subtitle':
          'Penjadwalan interview, feedback interviewer, dan manajemen job offer.',
      'recruitment_ops_tab_scheduling': 'Penjadwalan',
      'recruitment_ops_tab_feedback': 'Feedback',
      'recruitment_ops_tab_offers': 'Penawaran',
      'recruitment_ops_interview_schedule': 'Jadwal Interview',
      'recruitment_ops_interview_register': 'Register Interview',
      'recruitment_ops_interviewer_feedback': 'Feedback Interviewer',
      'recruitment_ops_feedback_register': 'Register Feedback',
      'recruitment_ops_offer_management': 'Manajemen Penawaran',
      'recruitment_ops_offer_tracker': 'Tracker Penawaran',
      'recruitment_ops_select_candidate': 'Pilih kandidat',
      'recruitment_ops_select_interviewer': 'Pilih interviewer',
      'recruitment_ops_select_schedule': 'Pilih jadwal',
      'recruitment_ops_no_position': 'Tidak ada posisi',
      'recruitment_ops_candidate': 'Kandidat',
      'recruitment_ops_position': 'Posisi',
      'recruitment_ops_interviewer': 'Interviewer',
      'recruitment_ops_schedule': 'Jadwal',
      'recruitment_ops_status': 'Status',
      'recruitment_ops_action': 'Aksi',
      'recruitment_ops_interview_type': 'Tipe interview',
      'recruitment_ops_duration_minutes': 'Durasi menit',
      'recruitment_ops_location': 'Lokasi',
      'recruitment_ops_meeting_link': 'Link rapat',
      'recruitment_ops_notes': 'Catatan',
      'recruitment_ops_save_schedule': 'Simpan Jadwal',
      'recruitment_ops_loading_schedules': 'Memuat jadwal...',
      'recruitment_ops_no_schedules': 'Belum ada jadwal interview.',
      'recruitment_ops_delete': 'Hapus',
      'recruitment_ops_status_scheduled': 'Dijadwalkan',
      'recruitment_ops_status_rescheduled': 'Dijadwalkan Ulang',
      'recruitment_ops_status_completed': 'Selesai',
      'recruitment_ops_status_cancelled': 'Dibatalkan',
      'recruitment_ops_delete_schedule_success': 'Jadwal interview dihapus',
      'recruitment_ops_schedule_saved': 'Jadwal interview disimpan',
      'recruitment_ops_schedule_required':
          'Pilih kandidat dan jadwal interview.',
      'recruitment_ops_rating': 'Rating {value}',
      'recruitment_ops_recommendation': 'Rekomendasi',
      'recruitment_ops_recommendation_strong_yes': 'Sangat Ya',
      'recruitment_ops_recommendation_yes': 'Ya',
      'recruitment_ops_recommendation_hold': 'Tahan',
      'recruitment_ops_recommendation_no': 'Tidak',
      'recruitment_ops_strengths': 'Kekuatan',
      'recruitment_ops_concerns': 'Catatan Risiko',
      'recruitment_ops_summary': 'Ringkasan',
      'recruitment_ops_save_feedback': 'Simpan Feedback',
      'recruitment_ops_feedback_saved': 'Feedback interview disimpan',
      'recruitment_ops_feedback_required': 'Pilih jadwal interview.',
      'recruitment_ops_interview': 'Interview',
      'recruitment_ops_no_feedback': 'Belum ada feedback.',
      'recruitment_ops_offered_position': 'Posisi ditawarkan',
      'recruitment_ops_proposed_salary': 'Gaji yang diusulkan',
      'recruitment_ops_start_date': 'Tanggal mulai',
      'recruitment_ops_salary': 'Gaji',
      'recruitment_ops_save_offer': 'Simpan Penawaran',
      'recruitment_ops_offer_saved': 'Job offer dibuat',
      'recruitment_ops_offer_status_updated': 'Status penawaran diperbarui',
      'recruitment_ops_offer_required':
          'Pilih kandidat, posisi, dan gaji penawaran.',
      'recruitment_ops_no_offers': 'Belum ada penawaran.',
      'recruitment_ops_update_status': 'Ubah Status',
      'recruitment_ops_draft': 'Draft',
      'recruitment_ops_sent': 'Terkirim',
      'recruitment_ops_accepted': 'Diterima',
      'recruitment_ops_withdrawn': 'Ditarik',
      'recruitment_ops_retry': 'Coba Lagi',
      'recruitment_ops_empty_dash': '-',
      'feature_label_employee_one': 'Karyawan Satu',
      'feature_label_inventory': 'Inventaris',
      'inventory_master': 'Master Inventori',
      'inventory_request_stock': 'Permintaan Pengeluaran',
      'inventory_receipt_stock': 'Penerimaan Stok',
      'inventory_report_stock': 'Laporan Inventori',
      'inventory_submenu_hint': 'Pilih menu inventori yang ingin dibuka.',
      'feature_label_training': 'Pelatihan',
      'people_development': 'Pengembangan SDM',
      'learning_lms': 'Pembelajaran & LMS',
      'talent_management': 'Manajemen Talenta',
      'employee_relations': 'Hubungan Karyawan',
      'people_development_submenu_hint':
          'Pilih menu pengembangan SDM yang ingin dibuka.',
      'feature_label_tasks': 'Tugas',
      'task_page_title': 'Tugas',
      'task_page_subtitle':
          'Kelola tugas pribadi dan tugas yang diberikan atasan ke bawahan.',
      'task_action_refresh': 'Muat Ulang',
      'task_action_add': 'Tambah Tugas',
      'task_action_edit': 'Edit',
      'task_action_delete': 'Hapus',
      'task_action_cancel': 'Batal',
      'task_action_save': 'Simpan',
      'task_action_create': 'Buat',
      'task_action_retry': 'Coba Lagi',
      'task_status_pending': 'Menunggu',
      'task_status_completed': 'Selesai',
      'task_metric_subordinate': 'Bawahan',
      'task_metric_overdue': 'Terlambat',
      'task_filter_all': 'Semua',
      'task_filter_mine': 'Saya',
      'task_filter_subordinate': 'Bawahan',
      'task_empty_title': 'Tidak ada tugas',
      'task_delete_title': 'Hapus Tugas',
      'task_delete_message': 'Hapus tugas "{title}"?',
      'task_delete_success': 'Tugas berhasil dihapus',
      'task_delete_failed': 'Gagal menghapus tugas',
      'task_status_to_pending': 'Tugas dipindahkan ke Menunggu',
      'task_status_to_completed': 'Tugas ditandai selesai',
      'task_status_update_failed': 'Gagal mengubah status tugas',
      'task_actions_tooltip': 'Aksi tugas',
      'task_form_create_title': 'Buat Tugas',
      'task_form_edit_title': 'Edit Tugas',
      'task_title_label': 'Judul',
      'task_description_label': 'Deskripsi',
      'task_title_required': 'Judul wajib diisi',
      'task_assignment_for': 'Tugas Untuk',
      'task_assignment_self': 'Diri Sendiri',
      'task_assignee_label': 'Penerima Tugas',
      'task_assignee_required': 'Pilih bawahan penerima tugas',
      'task_assignee_loading': 'Memuat daftar karyawan...',
      'task_assignee_empty': 'Tidak ada bawahan di daftar Anda',
      'task_assignee_note':
          'Penerima hanya dari daftar bawahan Anda. Jika bawahan dipilih, backend akan mengirim notifikasi.',
      'task_priority_label': 'Prioritas',
      'task_priority_high': 'Tinggi',
      'task_priority_medium': 'Sedang',
      'task_priority_low': 'Rendah',
      'task_type_label': 'Tipe',
      'task_type_regular': 'Reguler',
      'task_type_onboarding': 'Onboarding',
      'task_type_offboarding': 'Offboarding',
      'task_due_date_label': 'Tenggat',
      'task_due_prefix': 'Tenggat',
      'task_no_due_date': 'Tidak ada tenggat',
      'task_due_not_set': 'Belum diatur',
      'task_due_pick_date': 'Pilih Tanggal',
      'task_due_change_date': 'Ubah Tanggal',
      'task_due_clear': 'Hapus',
      'task_save_failed': 'Gagal menyimpan tugas',
      'task_create_success': 'Tugas berhasil dibuat',
      'task_update_success': 'Tugas berhasil diupdate',
      'task_toggle_complete_title': 'Selesaikan tugas ini?',
      'task_toggle_pending_title': 'Kembalikan ke Menunggu?',
      'task_toggle_complete_subtitle':
          'Tugas akan dipindahkan ke tab Selesai. Anda tetap bisa mengubahnya lagi nanti.',
      'task_toggle_pending_subtitle':
          'Tugas akan dipindahkan kembali ke tab Menunggu agar bisa dilanjutkan.',
      'task_toggle_complete_button': 'Ya, tandai selesai',
      'task_toggle_pending_button': 'Ya, ubah status',
      'task_toggle_cancel_complete': 'Belum dulu',
      'feature_label_time_tracking': 'Pelacakan Waktu',
      'feature_mobile_placeholder':
          'Menu ini sudah muncul sesuai permission akun Anda. Tampilan detail mobile untuk modul ini sedang disiapkan.',
      'feature_label_event_management': 'Rapat',
      'meeting_page_title': 'Rapat',
      'meeting_page_subtitle': 'Buat undangan rapat dan kelola peserta.',
      'meeting_create': 'Buat Rapat',
      'meeting_update': 'Perbarui Rapat',
      'meeting_edit': 'Edit',
      'meeting_delete': 'Hapus',
      'meeting_save': 'Simpan',
      'meeting_cancel': 'Batal',
      'meeting_retry': 'Coba Lagi',
      'meeting_empty': 'Belum ada rapat. Buat rapat pertama Anda.',
      'meeting_delete_title': 'Hapus Rapat',
      'meeting_delete_message': 'Hapus rapat "{title}"?',
      'meeting_delete_success': 'Rapat berhasil dihapus.',
      'meeting_delete_failed': 'Gagal menghapus rapat.',
      'meeting_company_wide': 'Semua karyawan',
      'meeting_invitee_count': '{count} peserta',
      'meeting_created_by': 'Dibuat oleh {name}',
      'meeting_form_create_title': 'Buat Rapat',
      'meeting_form_edit_title': 'Edit Rapat',
      'meeting_title_label': 'Judul Rapat',
      'meeting_title_required': 'Judul rapat wajib diisi.',
      'meeting_location_label': 'Lokasi',
      'meeting_location_hint': 'Ruang rapat / lokasi',
      'meeting_description_label': 'Pesan / Agenda',
      'meeting_description_hint': 'Tulis agenda rapat...',
      'meeting_start_label': 'Mulai',
      'meeting_end_label': 'Selesai',
      'meeting_optional': 'Opsional',
      'meeting_company_wide_title': 'Rapat untuk semua karyawan',
      'meeting_company_wide_subtitle':
          'Jika aktif, semua karyawan di perusahaan ini dapat melihat rapat.',
      'meeting_search_invitees': 'Cari karyawan untuk diundang',
      'meeting_invitees_title': 'Peserta ({count})',
      'meeting_no_invitees': 'Tidak ada karyawan yang bisa dipilih.',
      'meeting_invitee_required': 'Pilih minimal satu karyawan untuk diundang.',
      'meeting_save_failed': 'Gagal menyimpan rapat.',
      'meeting_clear_date': 'Hapus tanggal',
      'meeting_pick_date': 'Pilih tanggal',
      'feature_label_broadcast': 'Pengumuman',
      'broadcast_page_title': 'Pengumuman',
      'broadcast_compose_tab': 'Buat',
      'broadcast_history_tab': 'Riwayat',
      'broadcast_company_required_title': 'Pilih perusahaan terlebih dahulu',
      'broadcast_company_required_message':
          'Pengumuman membutuhkan perusahaan aktif agar data karyawan dan riwayat dapat dimuat dengan benar.',
      'broadcast_message_title': 'Pesan Pengumuman',
      'broadcast_message_subtitle':
          'Kirim pengumuman dan notifikasi ke karyawan sesuai hak akses.',
      'broadcast_company_badge': 'Perusahaan {code}',
      'broadcast_employee_restricted': 'karyawan dibatasi',
      'broadcast_employee_count': '{count} karyawan',
      'broadcast_department_restricted': 'departemen dibatasi',
      'broadcast_department_count': '{count} departemen',
      'broadcast_history_restricted': 'riwayat dibatasi',
      'broadcast_history_count': '{count} riwayat',
      'broadcast_recipients_restricted':
          'Pengumuman bisa dibuka, tetapi daftar penerima dibatasi oleh akses data karyawan/departemen.',
      'broadcast_compose_title': 'Susun Pesan',
      'broadcast_compose_subtitle':
          'Tulis judul, isi pesan, dan prioritas pengumuman.',
      'broadcast_title_hint': 'Masukkan judul pengumuman',
      'broadcast_message_hint': 'Tulis pesan yang ingin dikirim...',
      'broadcast_character_count': '{count} karakter',
      'broadcast_priority_hint': 'Pilih prioritas',
      'broadcast_priority_low_full': 'Prioritas Rendah',
      'broadcast_priority_medium_full': 'Prioritas Sedang',
      'broadcast_priority_high_full': 'Prioritas Tinggi',
      'broadcast_priority_low': 'Rendah',
      'broadcast_priority_medium': 'Sedang',
      'broadcast_priority_high': 'Tinggi',
      'broadcast_priority_help':
          'Prioritas tinggi akan lebih mudah terlihat oleh penerima.',
      'broadcast_type_title': 'Jenis Pengumuman',
      'broadcast_type_subtitle':
          'Pilih Agenda Kalender jika pengumuman juga harus masuk kalender kantor.',
      'broadcast_type_message': 'Pesan',
      'broadcast_type_event': 'Agenda Kalender',
      'broadcast_event_start': 'Mulai',
      'broadcast_event_end': 'Selesai',
      'broadcast_event_location_hint': 'Lokasi atau link rapat',
      'broadcast_pick_time': 'Pilih waktu',
      'broadcast_select_recipients_title': 'Pilih Penerima',
      'broadcast_select_recipients_subtitle':
          'Tentukan siapa yang akan menerima pengumuman ini.',
      'broadcast_all_employees': 'Semua Karyawan',
      'broadcast_all_employees_subtitle':
          'Kirim ke semua karyawan aktif yang tersedia di perusahaan.',
      'broadcast_access_limited': 'akses dibatasi',
      'broadcast_recipient_count': '{count} penerima',
      'broadcast_specific_departments': 'Departemen Tertentu',
      'broadcast_specific_departments_subtitle':
          'Pilih satu atau beberapa departemen tertentu.',
      'broadcast_selected_count': '{count} dipilih',
      'broadcast_choose_departments': 'Pilih Departemen',
      'broadcast_no_departments_selected': 'Belum ada departemen yang dipilih.',
      'broadcast_specific_employees': 'Karyawan Tertentu',
      'broadcast_specific_employees_subtitle':
          'Pilih karyawan satu per satu untuk pengumuman.',
      'broadcast_choose_employees': 'Pilih Karyawan',
      'broadcast_no_employees_selected': 'Belum ada karyawan yang dipilih.',
      'broadcast_summary_title': 'Ringkasan Penerima',
      'broadcast_summary_subtitle':
          'Ringkasan penerima sebelum pengumuman dikirim.',
      'broadcast_audience': 'Audiens',
      'broadcast_priority': 'Prioritas',
      'broadcast_total_recipients': 'Total Penerima',
      'broadcast_preview': 'Pratinjau',
      'broadcast_send': 'Kirim Pengumuman',
      'broadcast_sending': 'Mengirim...',
      'broadcast_history_title': 'Riwayat Pengumuman',
      'broadcast_history_subtitle':
          'Pantau pesan yang sudah pernah dikirim ke karyawan.',
      'broadcast_entry_count': '{count} entri',
      'broadcast_sent_count': '{count} terkirim',
      'broadcast_pending_count': '{count} tertunda',
      'broadcast_failed_count': '{count} gagal',
      'broadcast_history_permission_message':
          'Riwayat pengumuman tidak dimuat karena akses riwayat belum tersedia.',
      'broadcast_no_history_title': 'Belum ada riwayat',
      'broadcast_no_history_subtitle':
          'Pengumuman yang berhasil dikirim akan muncul di sini.',
      'broadcast_no_history_message': 'Belum ada pengumuman yang tercatat.',
      'broadcast_calendar_event': 'Agenda Kalender',
      'broadcast_recipients': '{count} penerima',
      'broadcast_title_message_required':
          'Judul dan pesan pengumuman wajib diisi.',
      'broadcast_recipient_required': 'Pilih minimal satu penerima pengumuman.',
      'broadcast_event_start_required':
          'Tanggal dan jam mulai agenda kalender wajib diisi.',
      'broadcast_send_failed': 'Pengumuman gagal dikirim.',
      'broadcast_calendar_success':
          'Pengumuman agenda kalender berhasil dikirim dan masuk kalender.',
      'broadcast_success': 'Pengumuman berhasil dikirim.',
      'broadcast_preview_title': 'Pratinjau Pengumuman',
      'broadcast_preview_no_title': '(Tanpa judul)',
      'broadcast_preview_empty_message': '(Pesan masih kosong)',
      'broadcast_close': 'Tutup',
      'broadcast_select_departments_title': 'Pilih Departemen',
      'broadcast_select_departments_subtitle':
          'Pilih departemen yang akan menerima pengumuman.',
      'broadcast_select_all': 'Pilih Semua',
      'broadcast_clear': 'Bersihkan',
      'broadcast_no_department_data': 'Data departemen belum tersedia.',
      'broadcast_employee_suffix': '{count} karyawan',
      'broadcast_apply_selection': 'Terapkan Pilihan',
      'broadcast_select_employees_title': 'Pilih Karyawan',
      'broadcast_select_employees_subtitle':
          'Cari dan pilih karyawan tertentu untuk menerima pengumuman.',
      'broadcast_employee_search_hint':
          'Cari nama, email, NIK, atau departemen',
      'broadcast_select_result': 'Pilih Hasil',
      'broadcast_no_employee_match': 'Tidak ada karyawan yang cocok.',
      'broadcast_no_department': 'Tanpa departemen',
      'broadcast_history_type_departments': 'Departemen',
      'broadcast_history_type_custom': 'Karyawan Tertentu',
      'broadcast_history_type_all': 'Semua Karyawan',
      'broadcast_status_sent': 'Terkirim',
      'broadcast_status_pending': 'Tertunda',
      'broadcast_status_failed': 'Gagal',
      'feature_label_documents': 'Dokumen',
      'feature_label_discovery': 'Discovery',
      'feature_label_reports': 'Laporan',
      'feature_label_bot_assistant': 'BOT Assistant',
      'feature_label_clients': 'Klien',
      'feature_label_corrections': 'Koreksi',
      'feature_no_correction_access':
          'Anda belum memiliki akses ke submenu koreksi.',
      'correction_submenu_hint': 'Pilih jenis koreksi yang ingin dibuka.',
      'correction_attendance': 'Koreksi Absensi',
      'correction_allowance': 'Koreksi Tunjangan',
      'correction_payroll': 'Koreksi Payroll',
      'correction_leave_balance': 'Koreksi Saldo Cuti',
      'feature_label_saas': 'Workspace SaaS',
      'feature_admin_submenu_hint': 'Pilih menu pengaturan yang ingin dibuka.',
      'admin_panel': 'Panel Admin',
      'admin_no_access_message':
          'Role Anda belum memiliki permission admin. Hubungi administrator untuk menambahkan akses yang dibutuhkan.',
      'admin_header_subtitle':
          'Menu yang tampil disesuaikan dengan hak akses akun Anda.',
      'admin_quick_actions': 'Aksi Cepat',
      'admin_modules': 'Modul',
      'admin_permissions': 'Permission',
      'admin_quick_add_employee': 'Tambah',
      'admin_quick_shift': 'Shift',
      'admin_quick_leave': 'Manajemen Cuti',
      'admin_quick_reports': 'Laporan',
      'admin_section_master_data': 'Master Data',
      'admin_section_configuration': 'Pengaturan',
      'admin_section_management': 'Manajemen',
      'admin_master_department': 'Departemen',
      'admin_master_department_subtitle': 'Kelola data departemen',
      'admin_master_employee': 'Karyawan',
      'admin_master_employee_subtitle': 'Kelola data karyawan',
      'admin_org_structure': 'Struktur Organisasi',
      'admin_org_structure_subtitle': 'Lihat hirarki supervisor dan bawahan',
      'admin_common_master': 'Master Data Umum',
      'admin_common_master_subtitle':
          'Master perusahaan, PTKP, tarif progresif, dan grup user',
      'admin_user_management': 'Manajemen User',
      'admin_user_management_subtitle':
          'Master permission, role, dan assignment user',
      'admin_master_shift': 'Master Shift',
      'admin_master_shift_subtitle': 'Buat dan ubah master shift',
      'admin_master_shift_day': 'Master Shift Harian',
      'settings_general': 'Pengaturan Umum',
      'admin_attendance_settings': 'Pengaturan Absensi',
      'admin_attendance_settings_subtitle': 'Atur radius dan lokasi absensi',
      'admin_shift_assignment': 'Shift Assignment',
      'admin_shift_assignment_subtitle': 'Buat dan pantau penugasan shift',
      'admin_leave_management': 'Leave Management',
      'admin_leave_management_subtitle': 'Tinjau dan setujui pengajuan cuti',
      'admin_correction_management': 'Correction Management',
      'admin_correction_management_subtitle':
          'Tinjau pengajuan koreksi absensi',
      'admin_claim_management': 'Claim Management',
      'admin_claim_management_subtitle': 'Tinjau dan setujui klaim karyawan',
      'admin_claim_reports': 'Claim Reports',
      'admin_claim_reports_subtitle': 'Analitik klaim dan reimbursement',
      'admin_broadcast': 'Pengumuman',
      'admin_broadcast_subtitle':
          'Kirim pengumuman ke semua karyawan atau penerima tertentu',
      'admin_event_management': 'Rapat',
      'admin_event_management_subtitle':
          'Buat rapat dan kelola penerima undangan',
      'admin_badge_master': 'Master',
      'admin_badge_active': 'Aktif',
      'admin_badge_config': 'Config',
      'admin_badge_policy': 'Kebijakan',
      'admin_badge_schedule': 'Jadwal',
      'admin_badge_approval': 'Approval',
      'admin_badge_review': 'Review',
      'admin_badge_finance': 'Keuangan',
      'admin_badge_insight': 'Insight',
      'admin_badge_broadcast': 'Pengumuman',
      'admin_badge_calendar': 'Kalender',
      'admin_menu_count': '{count} menu',
      'profile_account': 'Akun',
      'profile_app_settings': 'Pengaturan Aplikasi',
      'profile_support': 'Bantuan',
      'profile_personal_information': 'Informasi Pribadi',
      'profile_personal_information_subtitle': 'Perbarui detail pribadi Anda',
      'profile_employment_details': 'Detail Pekerjaan',
      'profile_employment_details_subtitle': 'Lihat informasi pekerjaan Anda',
      'profile_change_password': 'Ganti Password',
      'profile_change_password_subtitle': 'Perbarui password Anda',
      'profile_dark_mode': 'Mode Gelap',
      'profile_dark_mode_to_light': 'Ganti ke tema terang',
      'profile_dark_mode_to_dark': 'Ganti ke tema gelap',
      'profile_notifications': 'Notifikasi',
      'profile_notifications_subtitle': 'Atur notifikasi Anda',
      'profile_language': 'Bahasa',
      'profile_help_center': 'Pusat Bantuan',
      'profile_help_center_subtitle': 'Dapatkan bantuan dan dukungan',
      'profile_about_app': 'Tentang Aplikasi',
      'profile_privacy_policy': 'Kebijakan Privasi',
      'profile_privacy_policy_subtitle': 'Baca kebijakan privasi kami',
      'profile_logout': 'Keluar',
      'profile_logout_title': 'Keluar',
      'profile_logout_message': 'Apakah Anda yakin ingin keluar?',
      'profile_cancel': 'Batal',
      'profile_leave': 'Cuti',
      'profile_overtime': 'Lembur',
      'profile_rating': 'Rating',
      'profile_user_fallback': 'Pengguna',
      'profile_employee_fallback': 'Karyawan',
      'profile_select_language': 'Pilih Bahasa',
      'profile_language_subtitle': 'Ganti bahasa aplikasi',
      'profile_language_indonesian': 'Bahasa Indonesia',
      'profile_language_english': 'English',
      'profile_saas_workspace': 'SaaS Workspace',
      'profile_saas_workspace_subtitle':
          'Lihat status trial, invitation, dan akses multi-company.',
      'profile_switch_company_count': 'company terhubung',
      'saas_workspace_title': 'SaaS Workspace',
      'saas_workspace_subtitle':
          'Ringkasan trial, company aktif, dan invitation dari akun Anda.',
      'saas_loading': 'Memuat workspace SaaS...',
      'saas_open_workspace': 'Buka Workspace',
      'saas_current_company': 'Company Aktif',
      'saas_company_code': 'Company Code',
      'saas_company_not_selected': 'Belum ada company aktif',
      'saas_accessible_companies': 'Akses Company',
      'saas_accessible_companies_subtitle':
          'Daftar company yang bisa Anda buka dari akun ini.',
      'saas_trial_status': 'Status Trial',
      'saas_trial_unavailable': 'Belum tersedia',
      'saas_trial_expired': 'Trial berakhir',
      'saas_trial_active': 'Trial aktif',
      'saas_trial_days': 'Trial {count} hari',
      'saas_trial_days_remaining': 'Sisa {count} hari trial',
      'saas_grace_period': 'Grace period',
      'saas_active_plan': 'Paket aktif',
      'saas_days_remaining': 'Sisa hari',
      'saas_pending_invitations': 'Invitation Pending',
      'saas_invitations': 'Company Invitations',
      'saas_invitations_subtitle':
          'Undangan yang masih terkait dengan akses company Anda.',
      'saas_send_invitation': 'Kirim Undangan',
      'saas_send_invitation_subtitle':
          'Undang user manual atau SSO ke company aktif.',
      'saas_invitation_email': 'Email',
      'saas_invitation_email_hint': 'nama@company.com',
      'saas_invitation_name': 'Nama',
      'saas_invitation_name_hint': 'Nama penerima undangan',
      'saas_invitation_role': 'Role di Company',
      'saas_invitation_auth_mode': 'Mode Login',
      'saas_auth_either': 'Manual atau SSO',
      'saas_auth_manual': 'Manual saja',
      'saas_auth_sso_only': 'SSO saja',
      'saas_invitation_delivery_note':
          'Backend akan mengirim email invitation otomatis ke alamat tersebut.',
      'saas_invitation_email_required': 'Email undangan wajib diisi.',
      'saas_invitation_sent': 'Undangan berhasil dikirim.',
      'saas_invitation_failed': 'Gagal mengirim undangan.',
      'saas_invitation_token_copied': 'Token undangan berhasil disalin.',
      'saas_copy_invitation_token': 'Salin Token',
      'saas_revoke_invitation': 'Batalkan',
      'saas_revoking_invitation': 'Membatalkan...',
      'saas_invitation_revoked': 'Undangan berhasil dibatalkan.',
      'saas_invitation_revoke_failed': 'Gagal membatalkan undangan.',
      'saas_role_unknown': 'role belum tersedia',
      'saas_no_companies':
          'Belum ada company tambahan yang terhubung ke akun ini.',
      'saas_no_invitations': 'Belum ada invitation aktif.',
      'saas_company_active': 'Aktif',
      'saas_switch_company': 'Ganti',
      'saas_switch_success': 'Company aktif diganti ke {code}.',
      'saas_switch_failed': 'Gagal mengganti company aktif.',
      'saas_plan_unknown': 'status belum tersedia',
      'saas_invitation_auth_unknown': 'mode auth belum tersedia',
      'saas_status_unknown': 'unknown',
      'saas_expiry_unknown': 'tanpa tanggal kedaluwarsa',
      'saas_admin_snapshot': 'Snapshot Admin SaaS',
      'saas_admin_snapshot_subtitle':
          'Ringkasan global untuk akun platform admin.',
      'saas_pending_upgrades_global': 'Pending upgrade global',
      'saas_total_companies_global': 'Total company global',
      'personal_info_title': 'Informasi Pribadi',
      'personal_info_name': 'Nama Lengkap',
      'personal_info_email': 'Alamat Email',
      'personal_info_save': 'Simpan Perubahan',
      'personal_info_saved': 'Profil berhasil diperbarui',
      'personal_info_save_failed': 'Gagal memperbarui profil',
      'employment_title': 'Detail Pekerjaan',
      'employment_name': 'Nama',
      'employment_position': 'Posisi',
      'employment_employee_uuid': 'UUID Karyawan',
      'employment_selected_company': 'Perusahaan Terpilih',
      'employment_close': 'Tutup',
      'change_password_title': 'Ganti Password',
      'change_password_current': 'Password Saat Ini',
      'change_password_new': 'Password Baru',
      'change_password_confirm': 'Konfirmasi Password Baru',
      'change_password_button': 'Ganti Password',
      'change_password_mismatch': 'Password tidak sama',
      'change_password_required': 'wajib diisi',
      'change_password_min_length': 'Minimal 6 karakter',
      'change_password_hint': 'Password minimal harus 6 karakter',
      'change_password_success': 'Password berhasil diubah',
      'change_password_failed': 'Gagal mengubah password',
      'generic_error': 'Terjadi kesalahan',
      'generic_version': 'Versi 1.0.0',
    },
    'en': {
      'nav_home': 'Home',
      'nav_dashboard': 'Dashboard',
      'nav_features': 'Features',
      'nav_admin': 'Admin',
      'nav_approval': 'Approval',
      'nav_profile': 'Profile',
      'approval_subtitle': 'Your approvals and notification status',
      'approval_notification_title': 'Notifications',
      'approval_notification_unread': '{count} unread notifications',
      'approval_notification_summary': '{count} notifications available',
      'approval_action_section': 'Status & Approval',
      'approval_empty_title': 'No approval access yet',
      'approval_empty_message':
          'Menus will appear here when approval or transaction permissions are assigned.',
      'approval_badge_approve': 'APPROVE',
      'approval_badge_status': 'STATUS',
      'approval_leave_title': 'Leave',
      'approval_leave_subtitle': 'View leave status or process leave approval.',
      'approval_claims_title': 'Expense Claims',
      'approval_claims_subtitle':
          'Track claim status or process claim approval.',
      'approval_overtime_title': 'Overtime',
      'approval_overtime_subtitle':
          'Track overtime requests and approval status.',
      'approval_tasks_title': 'Tasks',
      'approval_tasks_subtitle': 'View your task status and progress.',
      'dashboard_cached_banner':
          'Dashboard is showing the latest cached data because the server cannot be reached right now.',
      'dashboard_stat_total_employees': 'Total Employees',
      'dashboard_stat_attendance_today': 'Today\'s Attendance',
      'dashboard_stat_on_leave_today': 'On Leave Today',
      'dashboard_stat_new_hires': 'New Hires',
      'dashboard_stat_active': 'Active',
      'dashboard_stat_present_today': 'Present today',
      'dashboard_stat_leave_today': 'Leave today',
      'dashboard_stat_this_month': 'This month',
      'dashboard_welcome_back': 'Welcome back,',
      'dashboard_good': 'Good',
      'dashboard_morning': 'morning',
      'dashboard_afternoon': 'afternoon',
      'dashboard_evening': 'evening',
      'dashboard_summary_today': 'Here is your summary for today',
      'dashboard_total_employees_short': 'total employees',
      'dashboard_quick_actions': 'Quick Actions',
      'dashboard_guide': 'Guide',
      'dashboard_quick_action_guide_title': 'Quick Action Guide',
      'dashboard_quick_action_guide_message':
          'Scan works best for QR attendance or branch checkpoints. While the dedicated scanner backend is not ready yet, the button currently opens Quick Clock In so it stays useful.',
      'dashboard_action_scan': 'Scan',
      'dashboard_action_scan_purpose':
          'Fastest access for QR attendance or office checkpoints. Right now it opens Quick Clock In.',
      'dashboard_action_leave': 'Leave',
      'dashboard_action_leave_purpose':
          'Go straight to leave requests and your leave history.',
      'dashboard_action_reports': 'Reports',
      'dashboard_action_reports_purpose':
          'Open claim and reimbursement reports to monitor team spending.',
      'dashboard_action_add_employee': 'Add Employee',
      'dashboard_action_add_employee_purpose':
          'Create a new employee without going through the deeper admin menu.',
      'dashboard_recent_activities': 'Recent Activities',
      'dashboard_view_all': 'View All',
      'dashboard_no_recent_activities': 'No recent activities',
      'dashboard_upcoming_events': 'Upcoming Meetings',
      'dashboard_manage': 'Manage',
      'dashboard_event_load_failed': 'Meetings could not be loaded yet.',
      'dashboard_retry': 'Retry',
      'dashboard_no_upcoming_events': 'No upcoming meetings yet.',
      'dashboard_event_empty_hint':
          'Create a meeting and choose invitees from Meeting.',
      'dashboard_create_event': 'Create Meeting',
      'dashboard_no_event_access':
          'Your account does not have access to Meeting.',
      'dashboard_all_employees': 'All employees',
      'dashboard_you_are_invited': 'You are invited',
      'dashboard_no_notifications': 'No notifications',
      'dashboard_notifications': 'Notifications',
      'dashboard_mark_all_read': 'Mark all as read',
      'dashboard_view_all_notifications': 'View all notifications ({count})',
      'dashboard_loading': 'Loading your dashboard...',
      'dashboard_error_title': 'Oops! Something went wrong',
      'dashboard_try_again': 'Try Again',
      'dashboard_just_now': 'Just now',
      'dashboard_minutes_ago': '{count} minute(s) ago',
      'dashboard_hours_ago': '{count} hour(s) ago',
      'dashboard_days_ago': '{count} day(s) ago',
      'dashboard_duration_label': 'Duration',
      'dashboard_duration_day': 'day',
      'dashboard_duration_days': 'days',
      'dashboard_today_label': 'Today',
      'dashboard_start_time': 'Start Time',
      'dashboard_end_time': 'End Time',
      'dashboard_record_time': 'Record Time',
      'dashboard_view_more': 'View More',
      'dashboard_hide_detail': 'Hide Detail',
      'dashboard_shift_label': 'Shift',
      'dashboard_favorite_menu': 'Favorite Menu',
      'dashboard_company_information': 'Company Information',
      'dashboard_attendance_ready': 'Ready to record',
      'dashboard_attendance_active': 'Checked in',
      'dashboard_attendance_complete': 'Attendance complete',
      'dashboard_attendance_pending_sync': 'Pending sync',
      'feature_no_active_title': 'No active features yet',
      'feature_no_active_message':
          'Your role does not have any active modules in the Feature tab yet. Contact an administrator if a module should be visible.',
      'feature_header_title': 'Explore Features',
      'feature_header_subtitle': 'Everything you need to manage your work',
      'feature_search_hint': 'Search features...',
      'feature_footer_count': '{count} features available',
      'feature_footer_subtitle':
          'Feature and Admin tabs now automatically follow your account permissions.',
      'feature_submenu_hint': 'Choose the submenu to open.',
      'feature_no_submenu_access':
          'Your account does not have access to available submenus yet.',
      'feature_submenu_available_count': '{count} menus available',
      'feature_empty_title': 'Feature not found',
      'feature_empty_search': 'No features match the search "{query}".',
      'feature_empty_all': 'No active features are available for your role.',
      'feature_empty_category':
          'No active features are available in the {category} category.',
      'feature_category_all': 'All',
      'feature_category_financial': 'Financial',
      'feature_category_core_hr': 'Core HR',
      'feature_category_operations': 'Operations',
      'feature_category_development': 'Development',
      'feature_category_workspace': 'Workspace',
      'feature_label_payroll': 'Payroll',
      'feature_label_payslip': 'Payslip',
      'payroll_settings': 'Payroll Settings',
      'payroll_menu_payroll': 'Payslip',
      'payroll_process': 'Payroll',
      'payroll_pph_report': 'PPh Report',
      'payroll_submenu_hint': 'Choose the payroll menu to open.',
      'feature_label_leave': 'Leave',
      'feature_label_attendance': 'Attendance',
      'feature_label_my_location': 'My Location',
      'feature_label_claims': 'Claims',
      'feature_label_overtime': 'Overtime',
      'feature_label_performance': 'Performance',
      'feature_label_kpi': 'KPI',
      'kpi_master': 'KPI Master',
      'kpi_evaluation_list': 'Evaluation List',
      'kpi_department_goals': 'Department Goal',
      'kpi_employee_goals': 'Employee Goal',
      'kpi_submenu_hint': 'Choose the KPI menu to open.',
      'kpi_mobile_placeholder':
          'This menu already follows your account permissions. The detailed mobile view for the KPI module is being prepared.',
      'feature_label_recruitment': 'Recruitment',
      'feature_label_applications': 'Applications',
      'feature_label_recruitment_ops': 'Recruitment Ops',
      'recruitment_page_title': 'Recruitment',
      'recruitment_page_subtitle':
          'Manage job postings and track candidate applications.',
      'recruitment_tab_pipeline': 'Pipeline',
      'recruitment_tab_applications': 'Applications',
      'recruitment_pipeline_title': 'Recruitment Pipeline',
      'recruitment_pipeline_subtitle':
          'Track open positions and candidate progress',
      'recruitment_candidate_pipeline': 'Candidate Pipeline',
      'recruitment_open_positions': 'Open Positions',
      'recruitment_no_open_positions': 'No open positions available.',
      'recruitment_recent_applications': 'Recent Applications',
      'recruitment_no_applications': 'No applications yet.',
      'recruitment_post_job': 'Post New Job',
      'recruitment_add_application': 'Add Application',
      'recruitment_new_application': 'New Application',
      'recruitment_select_department': 'Select Department',
      'recruitment_select_position': 'Select Position',
      'recruitment_select_urgency': 'Select Urgency',
      'recruitment_urgency_label': 'Urgency',
      'recruitment_urgency_high': 'High',
      'recruitment_urgency_medium': 'Medium',
      'recruitment_urgency_low': 'Low',
      'recruitment_job_requirements': 'Job Requirements',
      'recruitment_requirement_hint': 'Enter job requirements...',
      'recruitment_full_name': 'Full Name *',
      'recruitment_email': 'Email *',
      'recruitment_phone': 'Phone *',
      'recruitment_department': 'Department *',
      'recruitment_position': 'Position *',
      'recruitment_no_file_selected': 'No file selected',
      'recruitment_file_selected_success': 'File selected successfully',
      'recruitment_file_select_error': 'Error selecting file: {error}',
      'recruitment_supported_formats':
          'Supported formats: PDF, DOC, DOCX (Max 2MB)',
      'recruitment_fill_all_fields': 'Please fill all fields',
      'recruitment_fill_application_fields':
          'Please fill all fields and upload CV',
      'recruitment_job_posted_success': 'Job posted successfully',
      'recruitment_application_submitted_success':
          'Application submitted successfully',
      'recruitment_failed': 'Failed: {error}',
      'recruitment_unknown_error': 'Unknown error',
      'recruitment_error': 'Error: {error}',
      'recruitment_submit': 'Submit',
      'recruitment_save': 'Save',
      'recruitment_cancel': 'Cancel',
      'recruitment_update_status': 'Update Status',
      'recruitment_status_updated': 'Status updated to {status}',
      'recruitment_cv_unavailable': 'No CV available',
      'recruitment_cv_document': 'CV Document',
      'recruitment_cv_available': 'CV is available for download',
      'recruitment_download_started': 'Download started',
      'recruitment_download_cv': 'Download CV',
      'recruitment_close': 'Close',
      'recruitment_conversion_rate': 'Conversion Rate',
      'recruitment_avg_time_to_hire': 'Avg Time to Hire',
      'recruitment_days': 'days',
      'recruitment_position_not_specified': 'Position not specified',
      'recruitment_applied_prefix': 'Applied',
      'recruitment_view_cv': 'View CV',
      'recruitment_status_applied': 'Applied',
      'recruitment_status_screening': 'Screening',
      'recruitment_status_interview': 'Interview',
      'recruitment_status_offer': 'Offer',
      'recruitment_status_hired': 'Hired',
      'recruitment_status_rejected': 'Rejected',
      'recruitment_ops_page_title': 'Recruitment Operations',
      'recruitment_ops_page_subtitle':
          'Interview scheduling, interviewer feedback, and job offer management.',
      'recruitment_ops_tab_scheduling': 'Scheduling',
      'recruitment_ops_tab_feedback': 'Feedback',
      'recruitment_ops_tab_offers': 'Offers',
      'recruitment_ops_interview_schedule': 'Interview Schedule',
      'recruitment_ops_interview_register': 'Interview Register',
      'recruitment_ops_interviewer_feedback': 'Interviewer Feedback',
      'recruitment_ops_feedback_register': 'Feedback Register',
      'recruitment_ops_offer_management': 'Offer Management',
      'recruitment_ops_offer_tracker': 'Offer Tracker',
      'recruitment_ops_select_candidate': 'Select candidate',
      'recruitment_ops_select_interviewer': 'Select interviewer',
      'recruitment_ops_select_schedule': 'Select schedule',
      'recruitment_ops_no_position': 'No position',
      'recruitment_ops_candidate': 'Candidate',
      'recruitment_ops_position': 'Position',
      'recruitment_ops_interviewer': 'Interviewer',
      'recruitment_ops_schedule': 'Schedule',
      'recruitment_ops_status': 'Status',
      'recruitment_ops_action': 'Action',
      'recruitment_ops_interview_type': 'Interview type',
      'recruitment_ops_duration_minutes': 'Duration minutes',
      'recruitment_ops_location': 'Location',
      'recruitment_ops_meeting_link': 'Meeting link',
      'recruitment_ops_notes': 'Notes',
      'recruitment_ops_save_schedule': 'Save Schedule',
      'recruitment_ops_loading_schedules': 'Loading schedules...',
      'recruitment_ops_no_schedules': 'No interview schedules found.',
      'recruitment_ops_delete': 'Delete',
      'recruitment_ops_status_scheduled': 'Scheduled',
      'recruitment_ops_status_rescheduled': 'Rescheduled',
      'recruitment_ops_status_completed': 'Completed',
      'recruitment_ops_status_cancelled': 'Cancelled',
      'recruitment_ops_delete_schedule_success': 'Interview schedule deleted',
      'recruitment_ops_schedule_saved': 'Interview scheduled',
      'recruitment_ops_schedule_required':
          'Select a candidate and interview schedule.',
      'recruitment_ops_rating': 'Rating {value}',
      'recruitment_ops_recommendation': 'Recommendation',
      'recruitment_ops_recommendation_strong_yes': 'Strong Yes',
      'recruitment_ops_recommendation_yes': 'Yes',
      'recruitment_ops_recommendation_hold': 'Hold',
      'recruitment_ops_recommendation_no': 'No',
      'recruitment_ops_strengths': 'Strengths',
      'recruitment_ops_concerns': 'Concerns',
      'recruitment_ops_summary': 'Summary',
      'recruitment_ops_save_feedback': 'Save Feedback',
      'recruitment_ops_feedback_saved': 'Interview feedback saved',
      'recruitment_ops_feedback_required': 'Select an interview schedule.',
      'recruitment_ops_interview': 'Interview',
      'recruitment_ops_no_feedback': 'No feedback recorded.',
      'recruitment_ops_offered_position': 'Offered position',
      'recruitment_ops_proposed_salary': 'Proposed salary',
      'recruitment_ops_start_date': 'Start Date',
      'recruitment_ops_salary': 'Salary',
      'recruitment_ops_save_offer': 'Save Offer',
      'recruitment_ops_offer_saved': 'Job offer created',
      'recruitment_ops_offer_status_updated': 'Offer status updated',
      'recruitment_ops_offer_required':
          'Select candidate, offered position, and proposed salary.',
      'recruitment_ops_no_offers': 'No offers created.',
      'recruitment_ops_update_status': 'Update Status',
      'recruitment_ops_draft': 'Draft',
      'recruitment_ops_sent': 'Sent',
      'recruitment_ops_accepted': 'Accepted',
      'recruitment_ops_withdrawn': 'Withdrawn',
      'recruitment_ops_retry': 'Retry',
      'recruitment_ops_empty_dash': '-',
      'feature_label_employee_one': 'Employees One',
      'feature_label_inventory': 'Inventory',
      'inventory_master': 'Inventory Master',
      'inventory_request_stock': 'Request For Issued',
      'inventory_receipt_stock': 'Receipt Stock',
      'inventory_report_stock': 'Inventory Report',
      'inventory_submenu_hint': 'Choose the inventory menu you want to open.',
      'feature_label_training': 'Training',
      'people_development': 'People Development',
      'learning_lms': 'Learning & LMS',
      'talent_management': 'Talent Management',
      'employee_relations': 'Employee Relations',
      'people_development_submenu_hint':
          'Choose the people development menu to open.',
      'feature_label_tasks': 'Tasks',
      'task_page_title': 'Tasks',
      'task_page_subtitle':
          'Manage personal tasks and tasks assigned by managers to subordinates.',
      'task_action_refresh': 'Refresh',
      'task_action_add': 'Add Task',
      'task_action_edit': 'Edit',
      'task_action_delete': 'Delete',
      'task_action_cancel': 'Cancel',
      'task_action_save': 'Save',
      'task_action_create': 'Create',
      'task_action_retry': 'Retry',
      'task_status_pending': 'Pending',
      'task_status_completed': 'Completed',
      'task_metric_subordinate': 'Subordinates',
      'task_metric_overdue': 'Overdue',
      'task_filter_all': 'All',
      'task_filter_mine': 'Me',
      'task_filter_subordinate': 'Subordinates',
      'task_empty_title': 'No tasks found',
      'task_delete_title': 'Delete Task',
      'task_delete_message': 'Delete task "{title}"?',
      'task_delete_success': 'Task deleted successfully',
      'task_delete_failed': 'Failed to delete task',
      'task_status_to_pending': 'Task moved to Pending',
      'task_status_to_completed': 'Task marked completed',
      'task_status_update_failed': 'Failed to update task status',
      'task_actions_tooltip': 'Task actions',
      'task_form_create_title': 'Create Task',
      'task_form_edit_title': 'Edit Task',
      'task_title_label': 'Title',
      'task_description_label': 'Description',
      'task_title_required': 'Title is required',
      'task_assignment_for': 'Task For',
      'task_assignment_self': 'Self',
      'task_assignee_label': 'Task Recipient',
      'task_assignee_required': 'Choose a subordinate task recipient',
      'task_assignee_loading': 'Loading employees...',
      'task_assignee_empty': 'No subordinates in your list',
      'task_assignee_note':
          'Recipients are limited to your subordinate list. When a subordinate is selected, the backend will send a notification.',
      'task_priority_label': 'Priority',
      'task_priority_high': 'High',
      'task_priority_medium': 'Medium',
      'task_priority_low': 'Low',
      'task_type_label': 'Type',
      'task_type_regular': 'Regular',
      'task_type_onboarding': 'Onboarding',
      'task_type_offboarding': 'Offboarding',
      'task_due_date_label': 'Due Date',
      'task_due_prefix': 'Due',
      'task_no_due_date': 'No due date',
      'task_due_not_set': 'Not set',
      'task_due_pick_date': 'Pick Date',
      'task_due_change_date': 'Change Date',
      'task_due_clear': 'Clear',
      'task_save_failed': 'Failed to save task',
      'task_create_success': 'Task created successfully',
      'task_update_success': 'Task updated successfully',
      'task_toggle_complete_title': 'Complete this task?',
      'task_toggle_pending_title': 'Move back to Pending?',
      'task_toggle_complete_subtitle':
          'The task will move to the Completed tab. You can still change it again later.',
      'task_toggle_pending_subtitle':
          'The task will move back to the Pending tab so it can continue.',
      'task_toggle_complete_button': 'Yes, mark completed',
      'task_toggle_pending_button': 'Yes, update status',
      'task_toggle_cancel_complete': 'Not yet',
      'feature_label_time_tracking': 'Time Tracking',
      'feature_mobile_placeholder':
          'This menu is visible according to your account permissions. The mobile detail screen for this module is being prepared.',
      'feature_label_event_management': 'Meeting',
      'meeting_page_title': 'Meeting',
      'meeting_page_subtitle':
          'Create meeting invitations and manage participants.',
      'meeting_create': 'Create Meeting',
      'meeting_update': 'Update Meeting',
      'meeting_edit': 'Edit',
      'meeting_delete': 'Delete',
      'meeting_save': 'Save',
      'meeting_cancel': 'Cancel',
      'meeting_retry': 'Retry',
      'meeting_empty': 'No meetings yet. Create your first meeting.',
      'meeting_delete_title': 'Delete Meeting',
      'meeting_delete_message': 'Delete meeting "{title}"?',
      'meeting_delete_success': 'Meeting deleted successfully.',
      'meeting_delete_failed': 'Failed to delete meeting.',
      'meeting_company_wide': 'All employees',
      'meeting_invitee_count': '{count} participants',
      'meeting_created_by': 'Created by {name}',
      'meeting_form_create_title': 'Create Meeting',
      'meeting_form_edit_title': 'Edit Meeting',
      'meeting_title_label': 'Meeting Title',
      'meeting_title_required': 'Meeting title is required.',
      'meeting_location_label': 'Location',
      'meeting_location_hint': 'Meeting room / venue',
      'meeting_description_label': 'Message / Agenda',
      'meeting_description_hint': 'Write the meeting agenda...',
      'meeting_start_label': 'Start',
      'meeting_end_label': 'End',
      'meeting_optional': 'Optional',
      'meeting_company_wide_title': 'Company-wide meeting',
      'meeting_company_wide_subtitle':
          'When enabled, all employees in this company can see the meeting.',
      'meeting_search_invitees': 'Search employees to invite',
      'meeting_invitees_title': 'Participants ({count})',
      'meeting_no_invitees': 'No employees available to select.',
      'meeting_invitee_required': 'Select at least one employee to invite.',
      'meeting_save_failed': 'Failed to save meeting.',
      'meeting_clear_date': 'Clear date',
      'meeting_pick_date': 'Pick date',
      'feature_label_broadcast': 'Broadcast',
      'broadcast_page_title': 'Broadcast',
      'broadcast_compose_tab': 'Compose',
      'broadcast_history_tab': 'History',
      'broadcast_company_required_title': 'Select a company first',
      'broadcast_company_required_message':
          'Broadcast requires an active company so employee data and history can load correctly.',
      'broadcast_message_title': 'Broadcast Message',
      'broadcast_message_subtitle':
          'Send announcements and notifications to employees based on access.',
      'broadcast_company_badge': 'Company {code}',
      'broadcast_employee_restricted': 'employees restricted',
      'broadcast_employee_count': '{count} employees',
      'broadcast_department_restricted': 'departments restricted',
      'broadcast_department_count': '{count} departments',
      'broadcast_history_restricted': 'history restricted',
      'broadcast_history_count': '{count} history items',
      'broadcast_recipients_restricted':
          'Broadcast can be opened, but recipient lists are limited by employee/department data access.',
      'broadcast_compose_title': 'Compose Message',
      'broadcast_compose_subtitle':
          'Write the title, message, and broadcast priority.',
      'broadcast_title_hint': 'Enter broadcast title',
      'broadcast_message_hint': 'Write the message to send...',
      'broadcast_character_count': '{count} characters',
      'broadcast_priority_hint': 'Select priority',
      'broadcast_priority_low_full': 'Low Priority',
      'broadcast_priority_medium_full': 'Medium Priority',
      'broadcast_priority_high_full': 'High Priority',
      'broadcast_priority_low': 'Low',
      'broadcast_priority_medium': 'Medium',
      'broadcast_priority_high': 'High',
      'broadcast_priority_help':
          'High priority will be easier for recipients to notice.',
      'broadcast_type_title': 'Broadcast Type',
      'broadcast_type_subtitle':
          'Choose Calendar Event if this announcement should also appear in the office calendar.',
      'broadcast_type_message': 'Message',
      'broadcast_type_event': 'Calendar Event',
      'broadcast_event_start': 'Start',
      'broadcast_event_end': 'End',
      'broadcast_event_location_hint': 'Location or meeting link',
      'broadcast_pick_time': 'Pick time',
      'broadcast_select_recipients_title': 'Select Recipients',
      'broadcast_select_recipients_subtitle':
          'Choose who will receive this broadcast.',
      'broadcast_all_employees': 'All Employees',
      'broadcast_all_employees_subtitle':
          'Send to all active employees available in the company.',
      'broadcast_access_limited': 'access limited',
      'broadcast_recipient_count': '{count} recipients',
      'broadcast_specific_departments': 'Specific Departments',
      'broadcast_specific_departments_subtitle':
          'Choose one or more specific departments.',
      'broadcast_selected_count': '{count} selected',
      'broadcast_choose_departments': 'Choose Departments',
      'broadcast_no_departments_selected': 'No departments selected yet.',
      'broadcast_specific_employees': 'Specific Employees',
      'broadcast_specific_employees_subtitle':
          'Choose employees one by one for this broadcast.',
      'broadcast_choose_employees': 'Choose Employees',
      'broadcast_no_employees_selected': 'No employees selected yet.',
      'broadcast_summary_title': 'Recipient Summary',
      'broadcast_summary_subtitle':
          'Review recipients before the broadcast is sent.',
      'broadcast_audience': 'Audience',
      'broadcast_priority': 'Priority',
      'broadcast_total_recipients': 'Total Recipients',
      'broadcast_preview': 'Preview',
      'broadcast_send': 'Send Broadcast',
      'broadcast_sending': 'Sending...',
      'broadcast_history_title': 'Broadcast History',
      'broadcast_history_subtitle':
          'Track messages that have been sent to employees.',
      'broadcast_entry_count': '{count} entries',
      'broadcast_sent_count': '{count} sent',
      'broadcast_pending_count': '{count} pending',
      'broadcast_failed_count': '{count} failed',
      'broadcast_history_permission_message':
          'Broadcast history was not loaded because history access is not available yet.',
      'broadcast_no_history_title': 'No history yet',
      'broadcast_no_history_subtitle':
          'Successful broadcasts will appear here.',
      'broadcast_no_history_message': 'No broadcasts have been recorded yet.',
      'broadcast_calendar_event': 'Calendar Event',
      'broadcast_recipients': '{count} recipients',
      'broadcast_title_message_required':
          'Broadcast title and message are required.',
      'broadcast_recipient_required':
          'Select at least one broadcast recipient.',
      'broadcast_event_start_required':
          'Calendar event start date and time are required.',
      'broadcast_send_failed': 'Failed to send broadcast.',
      'broadcast_calendar_success':
          'Broadcast event sent successfully and added to the calendar.',
      'broadcast_success': 'Broadcast sent successfully.',
      'broadcast_preview_title': 'Preview Broadcast',
      'broadcast_preview_no_title': '(No title)',
      'broadcast_preview_empty_message': '(Message is still empty)',
      'broadcast_close': 'Close',
      'broadcast_select_departments_title': 'Select Departments',
      'broadcast_select_departments_subtitle':
          'Choose departments that will receive the broadcast.',
      'broadcast_select_all': 'Select All',
      'broadcast_clear': 'Clear',
      'broadcast_no_department_data': 'Department data is not available yet.',
      'broadcast_employee_suffix': '{count} employees',
      'broadcast_apply_selection': 'Apply Selection',
      'broadcast_select_employees_title': 'Select Employees',
      'broadcast_select_employees_subtitle':
          'Search and choose specific employees to receive the broadcast.',
      'broadcast_employee_search_hint':
          'Search name, email, NIK, or department',
      'broadcast_select_result': 'Select Result',
      'broadcast_no_employee_match': 'No employees match.',
      'broadcast_no_department': 'No department',
      'broadcast_history_type_departments': 'Departments',
      'broadcast_history_type_custom': 'Custom Employees',
      'broadcast_history_type_all': 'All Employees',
      'broadcast_status_sent': 'Sent',
      'broadcast_status_pending': 'Pending',
      'broadcast_status_failed': 'Failed',
      'feature_label_documents': 'Documents',
      'feature_label_discovery': 'Discovery',
      'feature_label_reports': 'Reports',
      'feature_label_bot_assistant': 'BOT Assistant',
      'feature_label_clients': 'Clients',
      'feature_label_corrections': 'Correction',
      'feature_no_correction_access':
          'You do not have access to correction submenus yet.',
      'correction_submenu_hint': 'Choose the correction type to open.',
      'correction_attendance': 'Attendance Correction',
      'correction_allowance': 'Allowance Correction',
      'correction_payroll': 'Payroll Correction',
      'correction_leave_balance': 'Leave Balance Correction',
      'feature_label_saas': 'SaaS Workspace',
      'feature_admin_submenu_hint':
          'Choose the settings menu you want to open.',
      'admin_panel': 'Admin Panel',
      'admin_no_access_message':
          'Your role does not have admin permission yet. Contact an administrator to add the required access.',
      'admin_header_subtitle':
          'Visible menus are adjusted to your account permissions.',
      'admin_quick_actions': 'Quick Actions',
      'admin_modules': 'Modules',
      'admin_permissions': 'Permissions',
      'admin_quick_add_employee': 'Add',
      'admin_quick_shift': 'Shift',
      'admin_quick_leave': 'Leave',
      'admin_quick_reports': 'Reports',
      'admin_section_master_data': 'Master Data',
      'admin_section_configuration': 'Settings',
      'admin_section_management': 'Management',
      'admin_master_department': 'Departments',
      'admin_master_department_subtitle': 'Manage department data',
      'admin_master_employee': 'Employees',
      'admin_master_employee_subtitle': 'Manage employee data',
      'admin_org_structure': 'Org Structure',
      'admin_org_structure_subtitle':
          'View supervisor and direct report hierarchy',
      'admin_common_master': 'Common Master File',
      'admin_common_master_subtitle':
          'Company, PTKP, progressive tax, and user group masters',
      'admin_user_management': 'User Management',
      'admin_user_management_subtitle':
          'Permission, role, and user assignment masters',
      'admin_master_shift': 'Master Shift',
      'admin_master_shift_subtitle': 'Create and update shift master data',
      'admin_master_shift_day': 'Day Shift Master File',
      'settings_general': 'General Setting',
      'admin_attendance_settings': 'Attendance Settings',
      'admin_attendance_settings_subtitle':
          'Configure radius and attendance locations',
      'admin_shift_assignment': 'Shift Assignment',
      'admin_shift_assignment_subtitle': 'Create and monitor shift assignments',
      'admin_leave_management': 'Leave Management',
      'admin_leave_management_subtitle': 'Review and approve leave requests',
      'admin_correction_management': 'Correction Management',
      'admin_correction_management_subtitle':
          'Review attendance correction requests',
      'admin_claim_management': 'Claim Management',
      'admin_claim_management_subtitle': 'Review and approve employee claims',
      'admin_claim_reports': 'Claim Reports',
      'admin_claim_reports_subtitle': 'Analytics for claims and reimbursements',
      'admin_broadcast': 'Broadcast',
      'admin_broadcast_subtitle':
          'Send announcements to all employees or selected recipients',
      'admin_event_management': 'Meeting',
      'admin_event_management_subtitle': 'Create meetings and manage invitees',
      'admin_badge_master': 'Master',
      'admin_badge_active': 'Active',
      'admin_badge_config': 'Config',
      'admin_badge_policy': 'Policy',
      'admin_badge_schedule': 'Schedule',
      'admin_badge_approval': 'Approval',
      'admin_badge_review': 'Review',
      'admin_badge_finance': 'Finance',
      'admin_badge_insight': 'Insight',
      'admin_badge_broadcast': 'Broadcast',
      'admin_badge_calendar': 'Calendar',
      'admin_menu_count': '{count} menu',
      'profile_account': 'Account',
      'profile_app_settings': 'App Settings',
      'profile_support': 'Support',
      'profile_personal_information': 'Personal Information',
      'profile_personal_information_subtitle': 'Update your personal details',
      'profile_employment_details': 'Employment Details',
      'profile_employment_details_subtitle': 'View your job information',
      'profile_change_password': 'Change Password',
      'profile_change_password_subtitle': 'Update your password',
      'profile_dark_mode': 'Dark Mode',
      'profile_dark_mode_to_light': 'Switch to light theme',
      'profile_dark_mode_to_dark': 'Switch to dark theme',
      'profile_notifications': 'Notifications',
      'profile_notifications_subtitle': 'Manage your notifications',
      'profile_language': 'Language',
      'profile_help_center': 'Help Center',
      'profile_help_center_subtitle': 'Get help and support',
      'profile_about_app': 'About App',
      'profile_privacy_policy': 'Privacy Policy',
      'profile_privacy_policy_subtitle': 'Read our privacy policy',
      'profile_logout': 'Log Out',
      'profile_logout_title': 'Log Out',
      'profile_logout_message': 'Are you sure you want to log out?',
      'profile_cancel': 'Cancel',
      'profile_leave': 'Leave',
      'profile_overtime': 'Overtime',
      'profile_rating': 'Rating',
      'profile_user_fallback': 'User',
      'profile_employee_fallback': 'Employee',
      'profile_select_language': 'Select Language',
      'profile_language_subtitle': 'Change app language',
      'profile_language_indonesian': 'Bahasa Indonesia',
      'profile_language_english': 'English',
      'profile_saas_workspace': 'SaaS Workspace',
      'profile_saas_workspace_subtitle':
          'Check trial status, invitations, and multi-company access.',
      'profile_switch_company_count': 'connected companies',
      'saas_workspace_title': 'SaaS Workspace',
      'saas_workspace_subtitle':
          'A compact summary for your trial, active company, and invitations.',
      'saas_loading': 'Loading the SaaS workspace...',
      'saas_open_workspace': 'Open Workspace',
      'saas_current_company': 'Active Company',
      'saas_company_code': 'Company Code',
      'saas_company_not_selected': 'No active company selected',
      'saas_accessible_companies': 'Company Access',
      'saas_accessible_companies_subtitle':
          'The companies this account can open.',
      'saas_trial_status': 'Trial Status',
      'saas_trial_unavailable': 'Unavailable',
      'saas_trial_expired': 'Trial expired',
      'saas_trial_active': 'Active trial',
      'saas_trial_days': 'Trial {count} days',
      'saas_trial_days_remaining': '{count} trial days remaining',
      'saas_grace_period': 'Grace period',
      'saas_active_plan': 'Active plan',
      'saas_days_remaining': 'Days remaining',
      'saas_pending_invitations': 'Pending invitations',
      'saas_invitations': 'Company Invitations',
      'saas_invitations_subtitle':
          'Invitations currently related to your company access.',
      'saas_send_invitation': 'Send Invitation',
      'saas_send_invitation_subtitle':
          'Invite manual or SSO users into the active company.',
      'saas_invitation_email': 'Email',
      'saas_invitation_email_hint': 'name@company.com',
      'saas_invitation_name': 'Name',
      'saas_invitation_name_hint': 'Invitee name',
      'saas_invitation_role': 'Company Role',
      'saas_invitation_auth_mode': 'Auth Mode',
      'saas_auth_either': 'Manual or SSO',
      'saas_auth_manual': 'Manual only',
      'saas_auth_sso_only': 'SSO only',
      'saas_invitation_delivery_note':
          'The backend will automatically send the invitation email.',
      'saas_invitation_email_required': 'Invitation email is required.',
      'saas_invitation_sent': 'Invitation sent successfully.',
      'saas_invitation_failed': 'Failed to send the invitation.',
      'saas_invitation_token_copied': 'Invitation token copied.',
      'saas_copy_invitation_token': 'Copy Token',
      'saas_revoke_invitation': 'Revoke',
      'saas_revoking_invitation': 'Revoking...',
      'saas_invitation_revoked': 'Invitation revoked successfully.',
      'saas_invitation_revoke_failed': 'Failed to revoke the invitation.',
      'saas_role_unknown': 'role unavailable',
      'saas_no_companies':
          'There are no additional companies connected to this account yet.',
      'saas_no_invitations': 'There are no active invitations yet.',
      'saas_company_active': 'Active',
      'saas_switch_company': 'Switch',
      'saas_switch_success': 'Active company switched to {code}.',
      'saas_switch_failed': 'Failed to switch the active company.',
      'saas_plan_unknown': 'status unavailable',
      'saas_invitation_auth_unknown': 'auth mode unavailable',
      'saas_status_unknown': 'unknown',
      'saas_expiry_unknown': 'no expiry date',
      'saas_admin_snapshot': 'SaaS Admin Snapshot',
      'saas_admin_snapshot_subtitle':
          'A global summary for platform admin accounts.',
      'saas_pending_upgrades_global': 'Global pending upgrades',
      'saas_total_companies_global': 'Global total companies',
      'personal_info_title': 'Personal Information',
      'personal_info_name': 'Full Name',
      'personal_info_email': 'Email Address',
      'personal_info_save': 'Save Changes',
      'personal_info_saved': 'Profile updated successfully',
      'personal_info_save_failed': 'Failed to update profile',
      'employment_title': 'Employment Details',
      'employment_name': 'Name',
      'employment_position': 'Position',
      'employment_employee_uuid': 'Employee UUID',
      'employment_selected_company': 'Selected Company',
      'employment_close': 'Close',
      'change_password_title': 'Change Password',
      'change_password_current': 'Current Password',
      'change_password_new': 'New Password',
      'change_password_confirm': 'Confirm New Password',
      'change_password_button': 'Change Password',
      'change_password_mismatch': 'Passwords do not match',
      'change_password_required': 'is required',
      'change_password_min_length': 'Must be at least 6 characters',
      'change_password_hint': 'Password must be at least 6 characters long',
      'change_password_success': 'Password changed successfully',
      'change_password_failed': 'Failed to change password',
      'generic_error': 'An error occurred',
      'generic_version': 'Version 1.0.0',
    },
  };

  static String of(BuildContext context, String key, {bool listen = true}) {
    final languageCode = Provider.of<LanguageProvider>(
      context,
      listen: listen,
    ).languageCode;

    return _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
  }
}

extension AppStringsBuildContext on BuildContext {
  String tr(String key) => AppStrings.of(this, key);
}
