import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../providers/language_provider.dart';

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _values = {
    'id': {
      'nav_dashboard': 'Dashboard',
      'nav_features': 'Fitur',
      'nav_admin': 'Admin',
      'nav_profile': 'Profil',
      'dashboard_cached_banner':
          'Dashboard sedang menampilkan data cache terakhir karena server belum bisa diakses.',
      'dashboard_stat_total_employees': 'Total Karyawan',
      'dashboard_stat_attendance_today': 'Absensi Hari Ini',
      'dashboard_stat_on_leave_today': 'Cuti Hari Ini',
      'dashboard_stat_new_hires': 'Karyawan Baru',
      'dashboard_stat_active': 'Aktif',
      'dashboard_stat_present_today': 'Hadir hari ini',
      'dashboard_stat_leave_today': 'Cuti hari ini',
      'dashboard_stat_this_month': 'Bulan ini',
      'dashboard_welcome_back': 'Selamat datang kembali,',
      'dashboard_good': 'Selamat',
      'dashboard_morning': 'pagi',
      'dashboard_afternoon': 'siang',
      'dashboard_evening': 'malam',
      'dashboard_summary_today': 'Berikut ringkasan Anda hari ini',
      'dashboard_total_employees_short': 'total karyawan',
      'dashboard_quick_actions': 'Aksi Cepat',
      'dashboard_guide': 'Panduan',
      'dashboard_quick_action_guide_title': 'Panduan Aksi Cepat',
      'dashboard_quick_action_guide_message':
          'Scan paling cocok dipakai untuk absensi QR atau checkpoint cabang. Saat backend scanner khusus belum ada, tombol itu diarahkan ke Clock In agar tetap berguna.',
      'dashboard_action_scan': 'Scan',
      'dashboard_action_scan_purpose':
          'Akses tercepat untuk QR attendance atau checkpoint kantor. Saat ini diarahkan ke Clock In cepat.',
      'dashboard_action_leave': 'Cuti',
      'dashboard_action_leave_purpose':
          'Masuk langsung ke pengajuan cuti dan riwayat cuti Anda.',
      'dashboard_action_reports': 'Laporan',
      'dashboard_action_reports_purpose':
          'Buka laporan claim dan reimbursement untuk monitoring pengeluaran tim.',
      'dashboard_action_add_employee': 'Tambah Karyawan',
      'dashboard_action_add_employee_purpose':
          'Input data karyawan baru tanpa masuk ke menu admin yang lebih dalam.',
      'dashboard_recent_activities': 'Aktivitas Terbaru',
      'dashboard_view_all': 'Lihat Semua',
      'dashboard_no_recent_activities': 'Belum ada aktivitas terbaru',
      'dashboard_upcoming_events': 'Event Mendatang',
      'dashboard_manage': 'Kelola',
      'dashboard_event_load_failed': 'Event belum bisa dimuat.',
      'dashboard_retry': 'Coba Lagi',
      'dashboard_no_upcoming_events': 'Belum ada event mendatang.',
      'dashboard_event_empty_hint':
          'Buat event lalu pilih siapa yang diundang dari Event Management.',
      'dashboard_create_event': 'Buat Event',
      'dashboard_no_event_access':
          'Akun Anda belum memiliki akses ke Event Management.',
      'dashboard_all_employees': 'Semua karyawan',
      'dashboard_you_are_invited': 'Anda diundang',
      'dashboard_no_notifications': 'Tidak ada notifikasi',
      'dashboard_notifications': 'Notifikasi',
      'dashboard_mark_all_read': 'Tandai semua sudah dibaca',
      'dashboard_view_all_notifications': 'Lihat semua notifikasi ({count})',
      'dashboard_loading': 'Memuat dashboard Anda...',
      'dashboard_error_title': 'Ups! Terjadi kesalahan',
      'dashboard_try_again': 'Coba Lagi',
      'dashboard_just_now': 'Baru saja',
      'dashboard_minutes_ago': '{count} menit yang lalu',
      'dashboard_hours_ago': '{count} jam yang lalu',
      'dashboard_days_ago': '{count} hari yang lalu',
      'dashboard_duration_label': 'Durasi',
      'dashboard_duration_day': 'hari',
      'dashboard_duration_days': 'hari',
      'feature_no_active_title': 'Belum ada fitur aktif',
      'feature_no_active_message':
          'Role Anda belum memiliki modul yang aktif di tab Feature. Hubungi administrator jika ada modul yang seharusnya muncul.',
      'feature_header_title': 'Jelajahi Fitur',
      'feature_header_subtitle':
          'Semua yang Anda butuhkan untuk mengelola pekerjaan',
      'feature_search_hint': 'Cari fitur...',
      'feature_footer_count': '{count} fitur tersedia',
      'feature_footer_subtitle':
          'Tab Feature dan Admin sekarang otomatis mengikuti permission akun Anda.',
      'feature_empty_title': 'Fitur tidak ditemukan',
      'feature_empty_search':
          'Tidak ada fitur yang cocok dengan pencarian "{query}".',
      'feature_empty_all':
          'Tidak ada fitur yang aktif untuk role Anda saat ini.',
      'feature_empty_category':
          'Tidak ada fitur aktif pada kategori {category}.',
      'feature_category_all': 'Semua',
      'feature_category_financial': 'Keuangan',
      'feature_category_core_hr': 'HR Inti',
      'feature_category_operations': 'Operasional',
      'feature_category_development': 'Pengembangan',
      'feature_label_payslip': 'Slip Gaji',
      'feature_label_leave': 'Cuti',
      'feature_label_attendance': 'Absensi',
      'feature_label_my_location': 'Lokasi Saya',
      'feature_label_claims': 'Klaim',
      'feature_label_performance': 'Performa',
      'feature_label_recruitment': 'Rekrutmen',
      'feature_label_inventory': 'Inventaris',
      'feature_label_training': 'Pelatihan',
      'feature_label_tasks': 'Tugas',
      'feature_label_documents': 'Dokumen',
      'feature_label_clients': 'Klien',
      'feature_label_corrections': 'Koreksi',
      'admin_panel': 'Panel Admin',
      'admin_no_access_message':
          'Role Anda belum memiliki permission admin. Hubungi administrator untuk menambahkan akses yang dibutuhkan.',
      'admin_header_subtitle':
          'Menu yang tampil disesuaikan dengan hak akses akun Anda.',
      'admin_quick_actions': 'Aksi Cepat',
      'admin_modules': 'Modul',
      'admin_permissions': 'Permission',
      'admin_quick_add_employee': 'Tambah',
      'admin_quick_shift': 'Shift',
      'admin_quick_leave': 'Cuti',
      'admin_quick_reports': 'Laporan',
      'admin_section_master_data': 'Master Data',
      'admin_section_configuration': 'Konfigurasi',
      'admin_section_management': 'Manajemen',
      'admin_master_department': 'Master Department',
      'admin_master_department_subtitle': 'Kelola departemen perusahaan',
      'admin_master_employee': 'Master Employee',
      'admin_master_employee_subtitle': 'Kelola karyawan dan profil',
      'admin_master_shift': 'Master Shift',
      'admin_master_shift_subtitle': 'Buat dan ubah master shift',
      'admin_attendance_settings': 'Pengaturan Absensi',
      'admin_attendance_settings_subtitle': 'Atur radius dan lokasi absensi',
      'admin_shift_assignment': 'Shift Assignment',
      'admin_shift_assignment_subtitle': 'Buat dan pantau penugasan shift',
      'admin_leave_management': 'Leave Management',
      'admin_leave_management_subtitle': 'Tinjau dan setujui pengajuan cuti',
      'admin_correction_management': 'Correction Management',
      'admin_correction_management_subtitle':
          'Tinjau pengajuan koreksi absensi',
      'admin_claim_management': 'Claim Management',
      'admin_claim_management_subtitle': 'Tinjau dan setujui klaim karyawan',
      'admin_claim_reports': 'Claim Reports',
      'admin_claim_reports_subtitle': 'Analitik klaim dan reimbursement',
      'admin_event_management': 'Event Management',
      'admin_event_management_subtitle':
          'Buat event dan kelola penerima undangan',
      'admin_badge_master': 'Master',
      'admin_badge_active': 'Aktif',
      'admin_badge_config': 'Config',
      'admin_badge_policy': 'Kebijakan',
      'admin_badge_schedule': 'Jadwal',
      'admin_badge_approval': 'Approval',
      'admin_badge_review': 'Review',
      'admin_badge_finance': 'Keuangan',
      'admin_badge_insight': 'Insight',
      'admin_badge_calendar': 'Kalender',
      'admin_menu_count': '{count} menu',
      'profile_account': 'Akun',
      'profile_app_settings': 'Pengaturan Aplikasi',
      'profile_support': 'Bantuan',
      'profile_personal_information': 'Informasi Pribadi',
      'profile_personal_information_subtitle': 'Perbarui detail pribadi Anda',
      'profile_employment_details': 'Detail Pekerjaan',
      'profile_employment_details_subtitle': 'Lihat informasi pekerjaan Anda',
      'profile_change_password': 'Ganti Password',
      'profile_change_password_subtitle': 'Perbarui password Anda',
      'profile_dark_mode': 'Mode Gelap',
      'profile_dark_mode_to_light': 'Ganti ke tema terang',
      'profile_dark_mode_to_dark': 'Ganti ke tema gelap',
      'profile_notifications': 'Notifikasi',
      'profile_notifications_subtitle': 'Atur notifikasi Anda',
      'profile_language': 'Bahasa',
      'profile_help_center': 'Pusat Bantuan',
      'profile_help_center_subtitle': 'Dapatkan bantuan dan dukungan',
      'profile_about_app': 'Tentang Aplikasi',
      'profile_privacy_policy': 'Kebijakan Privasi',
      'profile_privacy_policy_subtitle': 'Baca kebijakan privasi kami',
      'profile_logout': 'Keluar',
      'profile_logout_title': 'Keluar',
      'profile_logout_message': 'Apakah Anda yakin ingin keluar?',
      'profile_cancel': 'Batal',
      'profile_leave': 'Cuti',
      'profile_overtime': 'Lembur',
      'profile_rating': 'Rating',
      'profile_user_fallback': 'Pengguna',
      'profile_employee_fallback': 'Karyawan',
      'profile_select_language': 'Pilih Bahasa',
      'profile_language_subtitle': 'Ganti bahasa aplikasi',
      'profile_language_indonesian': 'Bahasa Indonesia',
      'profile_language_english': 'English',
      'personal_info_title': 'Informasi Pribadi',
      'personal_info_name': 'Nama Lengkap',
      'personal_info_email': 'Alamat Email',
      'personal_info_save': 'Simpan Perubahan',
      'personal_info_saved': 'Profil berhasil diperbarui',
      'personal_info_save_failed': 'Gagal memperbarui profil',
      'employment_title': 'Detail Pekerjaan',
      'employment_name': 'Nama',
      'employment_position': 'Posisi',
      'employment_employee_uuid': 'UUID Karyawan',
      'employment_selected_company': 'Perusahaan Terpilih',
      'employment_close': 'Tutup',
      'change_password_title': 'Ganti Password',
      'change_password_current': 'Password Saat Ini',
      'change_password_new': 'Password Baru',
      'change_password_confirm': 'Konfirmasi Password Baru',
      'change_password_button': 'Ganti Password',
      'change_password_mismatch': 'Password tidak sama',
      'change_password_required': 'wajib diisi',
      'change_password_min_length': 'Minimal 6 karakter',
      'change_password_hint': 'Password minimal harus 6 karakter',
      'change_password_success': 'Password berhasil diubah',
      'change_password_failed': 'Gagal mengubah password',
      'generic_error': 'Terjadi kesalahan',
      'generic_version': 'Versi 1.0.0',
    },
    'en': {
      'nav_dashboard': 'Dashboard',
      'nav_features': 'Features',
      'nav_admin': 'Admin',
      'nav_profile': 'Profile',
      'dashboard_cached_banner':
          'Dashboard is showing the latest cached data because the server cannot be reached right now.',
      'dashboard_stat_total_employees': 'Total Employees',
      'dashboard_stat_attendance_today': 'Today\'s Attendance',
      'dashboard_stat_on_leave_today': 'On Leave Today',
      'dashboard_stat_new_hires': 'New Hires',
      'dashboard_stat_active': 'Active',
      'dashboard_stat_present_today': 'Present today',
      'dashboard_stat_leave_today': 'Leave today',
      'dashboard_stat_this_month': 'This month',
      'dashboard_welcome_back': 'Welcome back,',
      'dashboard_good': 'Good',
      'dashboard_morning': 'morning',
      'dashboard_afternoon': 'afternoon',
      'dashboard_evening': 'evening',
      'dashboard_summary_today': 'Here is your summary for today',
      'dashboard_total_employees_short': 'total employees',
      'dashboard_quick_actions': 'Quick Actions',
      'dashboard_guide': 'Guide',
      'dashboard_quick_action_guide_title': 'Quick Action Guide',
      'dashboard_quick_action_guide_message':
          'Scan works best for QR attendance or branch checkpoints. While the dedicated scanner backend is not ready yet, the button currently opens Quick Clock In so it stays useful.',
      'dashboard_action_scan': 'Scan',
      'dashboard_action_scan_purpose':
          'Fastest access for QR attendance or office checkpoints. Right now it opens Quick Clock In.',
      'dashboard_action_leave': 'Leave',
      'dashboard_action_leave_purpose':
          'Go straight to leave requests and your leave history.',
      'dashboard_action_reports': 'Reports',
      'dashboard_action_reports_purpose':
          'Open claim and reimbursement reports to monitor team spending.',
      'dashboard_action_add_employee': 'Add Employee',
      'dashboard_action_add_employee_purpose':
          'Create a new employee without going through the deeper admin menu.',
      'dashboard_recent_activities': 'Recent Activities',
      'dashboard_view_all': 'View All',
      'dashboard_no_recent_activities': 'No recent activities',
      'dashboard_upcoming_events': 'Upcoming Events',
      'dashboard_manage': 'Manage',
      'dashboard_event_load_failed': 'Events could not be loaded yet.',
      'dashboard_retry': 'Retry',
      'dashboard_no_upcoming_events': 'No upcoming events yet.',
      'dashboard_event_empty_hint':
          'Create an event and choose invitees from Event Management.',
      'dashboard_create_event': 'Create Event',
      'dashboard_no_event_access':
          'Your account does not have access to Event Management.',
      'dashboard_all_employees': 'All employees',
      'dashboard_you_are_invited': 'You are invited',
      'dashboard_no_notifications': 'No notifications',
      'dashboard_notifications': 'Notifications',
      'dashboard_mark_all_read': 'Mark all as read',
      'dashboard_view_all_notifications': 'View all notifications ({count})',
      'dashboard_loading': 'Loading your dashboard...',
      'dashboard_error_title': 'Oops! Something went wrong',
      'dashboard_try_again': 'Try Again',
      'dashboard_just_now': 'Just now',
      'dashboard_minutes_ago': '{count} minute(s) ago',
      'dashboard_hours_ago': '{count} hour(s) ago',
      'dashboard_days_ago': '{count} day(s) ago',
      'dashboard_duration_label': 'Duration',
      'dashboard_duration_day': 'day',
      'dashboard_duration_days': 'days',
      'feature_no_active_title': 'No active features yet',
      'feature_no_active_message':
          'Your role does not have any active modules in the Feature tab yet. Contact an administrator if a module should be visible.',
      'feature_header_title': 'Explore Features',
      'feature_header_subtitle': 'Everything you need to manage your work',
      'feature_search_hint': 'Search features...',
      'feature_footer_count': '{count} features available',
      'feature_footer_subtitle':
          'Feature and Admin tabs now automatically follow your account permissions.',
      'feature_empty_title': 'Feature not found',
      'feature_empty_search': 'No features match the search "{query}".',
      'feature_empty_all': 'No active features are available for your role.',
      'feature_empty_category':
          'No active features are available in the {category} category.',
      'feature_category_all': 'All',
      'feature_category_financial': 'Financial',
      'feature_category_core_hr': 'Core HR',
      'feature_category_operations': 'Operations',
      'feature_category_development': 'Development',
      'feature_label_payslip': 'Payslip',
      'feature_label_leave': 'Leave',
      'feature_label_attendance': 'Attendance',
      'feature_label_my_location': 'My Location',
      'feature_label_claims': 'Claims',
      'feature_label_performance': 'Performance',
      'feature_label_recruitment': 'Recruitment',
      'feature_label_inventory': 'Inventory',
      'feature_label_training': 'Training',
      'feature_label_tasks': 'Tasks',
      'feature_label_documents': 'Documents',
      'feature_label_clients': 'Clients',
      'feature_label_corrections': 'Corrections',
      'admin_panel': 'Admin Panel',
      'admin_no_access_message':
          'Your role does not have admin permission yet. Contact an administrator to add the required access.',
      'admin_header_subtitle':
          'Visible menus are adjusted to your account permissions.',
      'admin_quick_actions': 'Quick Actions',
      'admin_modules': 'Modules',
      'admin_permissions': 'Permissions',
      'admin_quick_add_employee': 'Add',
      'admin_quick_shift': 'Shift',
      'admin_quick_leave': 'Leave',
      'admin_quick_reports': 'Reports',
      'admin_section_master_data': 'Master Data',
      'admin_section_configuration': 'Configuration',
      'admin_section_management': 'Management',
      'admin_master_department': 'Master Department',
      'admin_master_department_subtitle': 'Manage company departments',
      'admin_master_employee': 'Master Employee',
      'admin_master_employee_subtitle': 'Manage employees and profiles',
      'admin_master_shift': 'Master Shift',
      'admin_master_shift_subtitle': 'Create and update shift master data',
      'admin_attendance_settings': 'Attendance Settings',
      'admin_attendance_settings_subtitle':
          'Configure radius and attendance locations',
      'admin_shift_assignment': 'Shift Assignment',
      'admin_shift_assignment_subtitle': 'Create and monitor shift assignments',
      'admin_leave_management': 'Leave Management',
      'admin_leave_management_subtitle': 'Review and approve leave requests',
      'admin_correction_management': 'Correction Management',
      'admin_correction_management_subtitle':
          'Review attendance correction requests',
      'admin_claim_management': 'Claim Management',
      'admin_claim_management_subtitle': 'Review and approve employee claims',
      'admin_claim_reports': 'Claim Reports',
      'admin_claim_reports_subtitle': 'Analytics for claims and reimbursements',
      'admin_event_management': 'Event Management',
      'admin_event_management_subtitle': 'Create events and manage invitees',
      'admin_badge_master': 'Master',
      'admin_badge_active': 'Active',
      'admin_badge_config': 'Config',
      'admin_badge_policy': 'Policy',
      'admin_badge_schedule': 'Schedule',
      'admin_badge_approval': 'Approval',
      'admin_badge_review': 'Review',
      'admin_badge_finance': 'Finance',
      'admin_badge_insight': 'Insight',
      'admin_badge_calendar': 'Calendar',
      'admin_menu_count': '{count} menu',
      'profile_account': 'Account',
      'profile_app_settings': 'App Settings',
      'profile_support': 'Support',
      'profile_personal_information': 'Personal Information',
      'profile_personal_information_subtitle': 'Update your personal details',
      'profile_employment_details': 'Employment Details',
      'profile_employment_details_subtitle': 'View your job information',
      'profile_change_password': 'Change Password',
      'profile_change_password_subtitle': 'Update your password',
      'profile_dark_mode': 'Dark Mode',
      'profile_dark_mode_to_light': 'Switch to light theme',
      'profile_dark_mode_to_dark': 'Switch to dark theme',
      'profile_notifications': 'Notifications',
      'profile_notifications_subtitle': 'Manage your notifications',
      'profile_language': 'Language',
      'profile_help_center': 'Help Center',
      'profile_help_center_subtitle': 'Get help and support',
      'profile_about_app': 'About App',
      'profile_privacy_policy': 'Privacy Policy',
      'profile_privacy_policy_subtitle': 'Read our privacy policy',
      'profile_logout': 'Log Out',
      'profile_logout_title': 'Log Out',
      'profile_logout_message': 'Are you sure you want to log out?',
      'profile_cancel': 'Cancel',
      'profile_leave': 'Leave',
      'profile_overtime': 'Overtime',
      'profile_rating': 'Rating',
      'profile_user_fallback': 'User',
      'profile_employee_fallback': 'Employee',
      'profile_select_language': 'Select Language',
      'profile_language_subtitle': 'Change app language',
      'profile_language_indonesian': 'Bahasa Indonesia',
      'profile_language_english': 'English',
      'personal_info_title': 'Personal Information',
      'personal_info_name': 'Full Name',
      'personal_info_email': 'Email Address',
      'personal_info_save': 'Save Changes',
      'personal_info_saved': 'Profile updated successfully',
      'personal_info_save_failed': 'Failed to update profile',
      'employment_title': 'Employment Details',
      'employment_name': 'Name',
      'employment_position': 'Position',
      'employment_employee_uuid': 'Employee UUID',
      'employment_selected_company': 'Selected Company',
      'employment_close': 'Close',
      'change_password_title': 'Change Password',
      'change_password_current': 'Current Password',
      'change_password_new': 'New Password',
      'change_password_confirm': 'Confirm New Password',
      'change_password_button': 'Change Password',
      'change_password_mismatch': 'Passwords do not match',
      'change_password_required': 'is required',
      'change_password_min_length': 'Must be at least 6 characters',
      'change_password_hint': 'Password must be at least 6 characters long',
      'change_password_success': 'Password changed successfully',
      'change_password_failed': 'Failed to change password',
      'generic_error': 'An error occurred',
      'generic_version': 'Version 1.0.0',
    },
  };

  static String of(BuildContext context, String key) {
    final languageCode = Provider.of<LanguageProvider>(
      context,
      listen: true,
    ).languageCode;

    return _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
  }
}

extension AppStringsBuildContext on BuildContext {
  String tr(String key) => AppStrings.of(this, key);
}
